using System.Globalization;
using System.Security;
using System.Text;

namespace Dokany.DistributionProfile;

public static class DistributionProfileGenerator
{
    public static GeneratedDistributionProfile Render(DistributionProfile profile)
    {
        ArgumentNullException.ThrowIfNull(profile);
        if (string.IsNullOrEmpty(profile.ProfileHash))
        {
            throw new ArgumentException("Profile must be loaded through DistributionProfileLoader.", nameof(profile));
        }

        var runtimeIdentity = new RuntimeIdentityManifest(
            SchemaVersion: profile.SchemaVersion,
            DistributionId: profile.DistributionId,
            ProfileHash: profile.ProfileHash,
            ProductVersion: profile.Release.ProductVersion,
            ProtocolAbi: profile.Release.ProtocolAbi,
            Family: new RuntimeFamilyManifest(
                profile.Family.BinaryBaseName,
                profile.Family.ServiceName,
                profile.Derived.GlobalDeviceName,
                profile.Family.FamilyGuid,
                profile.Family.VolumeBaseGuid));

        return new GeneratedDistributionProfile(
            RenderHeader(profile),
            RenderRustConstants(profile),
            RenderMsBuildProps(profile),
            RenderInf(profile),
            $"{profile.Family.BinaryBaseName}.inf",
            RenderVersionXml(profile),
            runtimeIdentity);
    }

    private static string RenderRustConstants(DistributionProfile profile)
    {
        var profileHashBytes = Enumerable.Range(0, profile.ProfileHash.Length / 2)
            .Select(index => $"0x{profile.ProfileHash.Substring(index * 2, 2)}")
            .ToArray();
        return $$"""
            // Generated by tools/DistributionProfile. Do not edit.
            pub const DOKAN_DISTRIBUTION_ID: &str = "{{EscapeRustString(profile.DistributionId)}}";
            pub const DOKAN_BINARY_BASENAME: &str = "{{EscapeRustString(profile.Family.BinaryBaseName)}}";
            pub const DOKAN_RUNTIME_DLL_NAME: &str = "{{EscapeRustString(profile.Family.BinaryBaseName)}}.dll";
            pub const DOKAN_DRIVER_SERVICE_NAME: &str = "{{EscapeRustString(profile.Family.ServiceName)}}";
            pub const DOKAN_FAMILY_GUID: &str = "{{profile.Family.FamilyGuid}}";
            pub const DOKAN_PROFILE_HASH_HEX: &str = "{{profile.ProfileHash}}";
            pub const DOKAN_PROFILE_HASH: [u8; 32] = [{{string.Join(", ", profileHashBytes)}}];
            pub const DOKAN_PROTOCOL_ABI: u32 = {{profile.Release.ProtocolAbi}};
            pub const DOKAN_PRODUCT_VERSION: &str = "{{profile.Release.ProductVersion}}";
            """ + Environment.NewLine;
    }

    private static string RenderHeader(DistributionProfile profile)
    {
        var version = Version.Parse(profile.Release.ProductVersion);
        var profileHashBytes = Enumerable.Range(0, profile.ProfileHash.Length / 2)
            .Select(index => $"0x{profile.ProfileHash.Substring(index * 2, 2)}")
            .ToArray();

        return $$"""
            // Generated by tools/DistributionProfile. Do not edit.
            #ifndef DOKAN_DISTRIBUTION_PROFILE_H_
            #define DOKAN_DISTRIBUTION_PROFILE_H_

            #define DOKAN_DIST_SCHEMA_VERSION {{profile.SchemaVersion}}
            #define DOKAN_DIST_API_MAJOR {{profile.ApiMajor}}
            #define DOKAN_DIST_API_MAJOR_W L"{{profile.ApiMajor}}"
            #define DOKAN_DIST_DISTRIBUTION_ID_A "{{EscapeCString(profile.DistributionId)}}"
            #define DOKAN_DIST_DISTRIBUTION_ID_W L"{{EscapeCString(profile.DistributionId)}}"
            #define DOKAN_DIST_DISPLAY_NAME_W L"{{EscapeCString(profile.DisplayName)}}"
            #define DOKAN_DIST_PROVIDER_NAME_W L"{{EscapeCString(profile.ProviderName)}}"
            #define DOKAN_DIST_COMPANY_NAME_W L"{{EscapeCString(profile.CompanyName)}}"
            #define DOKAN_DIST_BINARY_BASENAME_A "{{EscapeCString(profile.Family.BinaryBaseName)}}"
            #define DOKAN_DIST_BINARY_BASENAME_W L"{{EscapeCString(profile.Family.BinaryBaseName)}}"
            #define DOKAN_DIST_DLL_FILENAME_W DOKAN_DIST_BINARY_BASENAME_W L".dll"
            #define DOKAN_DIST_DRIVER_FILENAME_W DOKAN_DIST_BINARY_BASENAME_W L".sys"
            #define DOKAN_DIST_CONTROL_BASENAME_W L"{{EscapeCString(profile.Family.ControlBaseName)}}"
            #define DOKAN_DIST_DRIVER_SERVICE_W L"{{EscapeCString(profile.Family.ServiceName)}}"
            #define DOKAN_DIST_DEVICE_PREFIX_W L"{{EscapeCString(profile.Family.DevicePrefix)}}"
            #define DOKAN_DIST_GLOBAL_DEVICE_WIN32_W L"\\\\.\\{{EscapeCString(profile.Derived.GlobalDeviceName)}}"
            #define DOKAN_DIST_GLOBAL_DEVICE_NT_W L"{{EscapeCString(profile.Derived.GlobalDeviceNtPath)}}"
            #define DOKAN_DIST_GLOBAL_SYMBOLIC_LINK_W L"{{EscapeCString(profile.Derived.GlobalSymbolicLinkName)}}"
            #define DOKAN_DIST_FS_DISK_DEVICE_W L"{{EscapeCString(profile.Derived.FileSystemDiskDeviceName)}}"
            #define DOKAN_DIST_FS_CD_DEVICE_W L"{{EscapeCString(profile.Derived.FileSystemCdDeviceName)}}"
            #define DOKAN_DIST_REDIRECTOR_DEVICE_W L"{{EscapeCString(profile.Derived.RedirectorDeviceName)}}"
            #define DOKAN_DIST_REDIRECTOR_SYMBOLIC_LINK_W L"{{EscapeCString(profile.Derived.RedirectorSymbolicLinkName)}}"
            #define DOKAN_DIST_EVENT_LOG_SOURCE_W L"{{EscapeCString(profile.Family.EventLogSource)}}"
            #define DOKAN_DIST_DRIVER_SYSTEM_PATH_W L"{{EscapeCString(profile.Derived.DriverSystemPath)}}"
            #define DOKAN_DIST_VOLUME_LABEL_W L"{{EscapeCString(profile.Family.VolumeLabel)}}"
            #define DOKAN_DIST_FAMILY_GUID_W L"{{profile.Family.FamilyGuid}}"
            #define DOKAN_DIST_FAMILY_GUID_INITIALIZER {{GuidInitializer(profile.Family.FamilyGuid)}}
            #define DOKAN_DIST_VOLUME_BASE_GUID_INITIALIZER {{GuidInitializer(profile.Family.VolumeBaseGuid)}}
            #define DOKAN_DIST_PROFILE_HASH_A "{{profile.ProfileHash}}"
            #define DOKAN_DIST_PROFILE_HASH_W L"{{profile.ProfileHash}}"
            #define DOKAN_DIST_PROFILE_HASH_BYTES { {{string.Join(", ", profileHashBytes)}} }
            #define DOKAN_DIST_PROTOCOL_ABI {{profile.Release.ProtocolAbi}}
            #define DOKAN_DIST_LIBRARY_VERSION {{version.Major * 100 + version.Minor * 10 + version.Build}}
            #define DOKAN_DIST_PRODUCT_VERSION_W L"{{profile.Release.ProductVersion}}"
            #define DOKAN_DIST_PRODUCT_VERSION_COMMA {{version.Major}},{{version.Minor}},{{version.Build}},{{version.Revision}}
            #define DOKAN_DIST_NETWORK_PROVIDER_ENABLED {{(profile.Family.NetworkProvider.Enabled ? 1 : 0)}}
            #define DOKAN_DIST_NETWORK_PROVIDER_NAME_W L"{{EscapeCString(profile.Family.NetworkProvider.Name)}}"
            #define DOKAN_DIST_NETWORK_PROVIDER_DLL_W L"{{EscapeCString(profile.Family.NetworkProvider.DllBaseName)}}"
            #define DOKAN_DIST_NETWORK_PROVIDER_FILENAME_W DOKAN_DIST_NETWORK_PROVIDER_DLL_W L".dll"

            #endif // DOKAN_DISTRIBUTION_PROFILE_H_
            """ + Environment.NewLine;
    }

    private static string RenderMsBuildProps(DistributionProfile profile)
    {
        var version = Version.Parse(profile.Release.ProductVersion);
        var baseVersion = $"{version.Major}.{version.Minor}.{version.Build}";
        return $$"""
            <?xml version="1.0" encoding="utf-8"?>
            <Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
              <PropertyGroup>
                <DokanDistributionId>{{Xml(profile.DistributionId)}}</DokanDistributionId>
                <DokanDistributionProfileHash>{{profile.ProfileHash}}</DokanDistributionProfileHash>
                <DOKANAPIVersion>{{profile.ApiMajor}}</DOKANAPIVersion>
                <DOKANVersion>{{baseVersion}}</DOKANVersion>
                <DokanProductVersion>{{profile.Release.ProductVersion}}</DokanProductVersion>
                <DokanBinaryBaseName>{{Xml(profile.Family.BinaryBaseName)}}</DokanBinaryBaseName>
                <DokanControlBaseName>{{Xml(profile.Family.ControlBaseName)}}</DokanControlBaseName>
                <DokanNetworkProviderBaseName>{{Xml(profile.Family.NetworkProvider.DllBaseName)}}</DokanNetworkProviderBaseName>
                <DokanNetworkProviderEnabled>{{profile.Family.NetworkProvider.Enabled.ToString().ToLowerInvariant()}}</DokanNetworkProviderEnabled>
                <DokanDriverServiceName>{{Xml(profile.Family.ServiceName)}}</DokanDriverServiceName>
                <DokanGeneratedInfFileName>{{Xml(profile.Family.BinaryBaseName)}}.inf</DokanGeneratedInfFileName>
              </PropertyGroup>
            </Project>
            """ + Environment.NewLine;
    }

    private static string RenderInf(DistributionProfile profile) => $$"""
        ; Generated by tools/DistributionProfile. Do not edit.
        [Version]
        Signature         = "$Windows NT$"
        Class             = DiskDrive
        ClassGuid         = {4d36e967-e325-11ce-bfc1-08002be10318}
        Provider          = %ProviderName%
        DriverVer         = 01/01/2018,1.0.0.0
        CatalogFile       = %DriverName%.cat
        DriverPackageType = FileSystem
        PnpLockdown       = 1

        [DestinationDirs]
        DefaultDestDir = 12

        [DefaultInstall.NT$ARCH$]
        CopyFiles = DokanFileSystem.DriverFiles

        [SourceDisksNames]
        1 = %Disk1%

        [SourceDisksFiles]
        {{profile.Family.BinaryBaseName}}.sys = 1

        [DokanFileSystem.DriverFiles]
        %DriverName%.sys

        [Strings]
        ProviderName       = "{{EscapeInf(profile.ProviderName)}}"
        DriverName         = "{{EscapeInf(profile.Family.BinaryBaseName)}}"
        Disk1              = "{{EscapeInf(profile.DisplayName)}} installation media"
        """ + Environment.NewLine;

    private static string RenderVersionXml(DistributionProfile profile)
    {
        var version = Version.Parse(profile.Release.ProductVersion);
        return $$"""
            <?xml version="1.0" encoding="utf-8"?>
            <Include>
            <?define ProductName="{{Xml(profile.DisplayName)}}" ?>
            <?define ProductCodeX64="{{Braced(profile.Installer.ProductCodeX64)}}" ?>
            <?define UpgradeCodeX64="{{Braced(profile.Installer.UpgradeCodeX64)}}" ?>
            <?define ProductCodeX86="{{Braced(profile.Installer.ProductCodeX86)}}" ?>
            <?define UpgradeCodeX86="{{Braced(profile.Installer.UpgradeCodeX86)}}" ?>
            <?define ProductCodeARM64="{{Braced(profile.Installer.ProductCodeArm64)}}" ?>
            <?define UpgradeCodeARM64="{{Braced(profile.Installer.UpgradeCodeArm64)}}" ?>
            <?define ProviderKey="{{Braced(profile.Installer.ProviderKey)}}" ?>
            <?define BundleUpgradeCode="{{Braced(profile.Installer.BundleUpgradeCode)}}" ?>
            <?define BaseVersion="{{version.Major}}.{{version.Minor}}.{{version.Build}}" ?>
            <?define MajorVersion="{{version.Major}}" ?>
            <?define BuildVersion="{{version.Revision.ToString("0000", CultureInfo.InvariantCulture)}}" ?>
            <?define CompanyName="{{Xml(profile.CompanyName)}}" ?>
            <?define ShortCompanyName="{{Xml(profile.CompanyName)}}" ?>
            <?define InstallerVersion="500" ?>
            <?define BuildCygwin="false" ?>
            </Include>
            """ + Environment.NewLine;
    }

    private static string GuidInitializer(string value)
    {
        var pieces = value.Split('-');
        var tail = pieces[3] + pieces[4];
        var bytes = Enumerable.Range(0, 8).Select(index => $"0x{tail.Substring(index * 2, 2).ToLowerInvariant()}");
        return $"{{ 0x{pieces[0].ToLowerInvariant()}, 0x{pieces[1].ToLowerInvariant()}, 0x{pieces[2].ToLowerInvariant()}, {{ {string.Join(", ", bytes)} }} }}";
    }

    private static string EscapeCString(string value) => value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
    private static string EscapeInf(string value) => value.Replace("\"", "\"\"", StringComparison.Ordinal);
    private static string EscapeRustString(string value) => value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
    private static string Xml(string value) => SecurityElement.Escape(value) ?? string.Empty;
    private static string Braced(string value) => $"{{{value.ToUpperInvariant()}}}";
}
